#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:white'
    background = 'transparent'
    template = "\u256d\u2500"
    
  [[blocks.segments]]
  	type = 'os'
  	style = 'diamond'
  	foreground = 'p:white'
    background = 'p:black'
  	leading_diamond = ""
  	template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'p:white'
    background = 'p:orange'
    template = " {{ .Path }} "

    [blocks.segments.properties]
      style = 'full'
      home_icon = "\uf015 "
      folder_icon = "\uf115"
      folder_seperator_icon = "\ue0b1" 
    
  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'p:black'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background = 'p:green'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true
 
[[blocks]]
  type = 'prompt'
  overflow = 'hidden'
  alignment = 'right'
  filler = "<p:white,transparent>—"

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = 'p:green'
    background = 'transparent'
    template = ' '

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'
    template = ' '

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    foreground = 'p:yellow'
    background = 'transparent'
    invert_powerline = true
    powerline_symbol = ''
    template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} \ue235 "

    [blocks.segments.properties]
      display_mode = 'context'
      fetch_version = true
      fetch_virtual_env = true
      display_default = true
      home_enabled = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = 'took {{ div .Ms 1000 }}s '

    [blocks.segments.properties]
      threshold = 5000
  
  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = 'p:white'
    background = 'p:blue'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    leading_diamond = ''
    trailing_diamond = '</>'
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

 
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

    [[blocks.segments]]
      type = 'text'
      style = 'plain'
      foreground = 'p:white'
      background = 'transparent'
      template = "\u2570\u2500"    

[[blocks]]
	type = 'rprompt'

	[[blocks.segment]]
	    type = "upgrade"
	    style = "plain"
	    foreground = "#111111"
	    background = "#FFD664"
	    template = "\uf019"


[transient_prompt]
  foreground = 'p:black'
  background = 'transparent'
  template = '<p:orange,transparent></><,p:orange> {{ .Folder }} </><p:orange,transparent></> '
  
[secondary_prompt]
  foreground = 'p:black'
  background = 'transparent'
  template = '<p:orange,transparent></><,p:orange> > </><p:orange,transparent></> '

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
